framereceiver:
  image: deasel011/frame:0.9.9
  ports:
    - "3001:3001"
    - "3001:3001/udp"
  links:
    - mongo:mongo
    - rabbitmq:rabbitmq
  volumes:
    - /log/
mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - /data/db
rabbitmq:
  image: rabbitmq
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
mongorest:
  image: deasel011/mongorest
  ports:
    - "8008:8008"
  links:
    - mongo:mongo
frameviewer:
  image: deasel011/frameviewer:0.0.1
  ports:
    - "3000:3000"
  links:
    - mongorest:mongorest
